export const newsItems = [
    {
      author: "Joe Bidenn",
      authorDescription: "I am giving back in the community.",
      content: "Hipster ipsum tattooed brunch I'm baby. Crucifix cliche mixtape salvia vexillologist. Kickstarter sartorial post-ironic biodiesel cold-pressed a activated subway. Af dsa kickstarter squid.",
      comments: 28,
      shares: 5,
      likes: 21,
    },
    {
      author: "Joe Bidenn",
      authorDescription: "I am giving back in the community.",
      content: "Hipster ipsum tattooed brunch I'm baby. Crucifix cliche mixtape salvia vexillologist. Kickstarter sartorial post-ironic biodiesel cold-pressed a activated subway. Af dsa kickstarter squid.",
      comments: 28,
      shares: 5,
      likes: 21,
    },
    {
      author: "Joe Bidenn",
      authorDescription: "I am giving back in the community.",
      content: "Hipster ipsum tattooed brunch I'm baby. Crucifix cliche mixtape salvia vexillologist. Kickstarter sartorial post-ironic biodiesel cold-pressed a activated subway. Af dsa kickstarter squid.",
      comments: 28,
      shares: 5,
      likes: 21,
    },
    {
      author: "Joe Bidenn",
      authorDescription: "I am giving back in the community.",
      content: "Hipster ipsum tattooed brunch I'm baby. Crucifix cliche mixtape salvia vexillologist. Kickstarter sartorial post-ironic biodiesel cold-pressed a activated subway. Af dsa kickstarter squid.",
      comments: 28,
      shares: 5,
      likes: 21,
    },
    {
      author: "Joe Bidenn",
      authorDescription: "I am giving back in the community.",
      content: "Hipster ipsum tattooed brunch I'm baby. Crucifix cliche mixtape salvia vexillologist. Kickstarter sartorial post-ironic biodiesel cold-pressed a activated subway. Af dsa kickstarter squid.",
      comments: 28,
      shares: 5,
      likes: 21,
    },
    {
      author: "Joe Bidenn",
      authorDescription: "I am giving back in the community.",
      content: "Hipster ipsum tattooed brunch I'm baby. Crucifix cliche mixtape salvia vexillologist. Kickstarter sartorial post-ironic biodiesel cold-pressed a activated subway. Af dsa kickstarter squid.",
      comments: 28,
      shares: 5,
      likes: 21,
    },
  ];